version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4300:4300"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --port 4300 --host
